---
title: "R Notebook"
output: html_notebook
---

# 1.Load data and initial inspections

```{r}
library(reader)
seatbelt = read.csv("seatbelt_group_14.csv")
seatbelt =data.frame(seatbelt)
head(seatbelt)
attach(seatbelt)

```


# 2.Cleaning  missing value
```{r}
summary(seatbelt)
```

```{r}
sum(is.na(seatbelt))

```

# 2.Cleaning  missing value

```{r}
seatbelt = subset(seatbelt, select = -state)
seatbelt
```
```{r}
seatbelt = subset(seatbelt, select = -seatbelt)
seatbelt
```

# 2.Cleaning  missing value


3.Data description and visualization:

## fatalities
```{r}
hist(fatalities, col ="blue",cex.lab =1.5, main = "fatalities",xlab = "fatalities")
```





# model building

## AIC
```{r}
library("MASS")
lm1 = lm(fatalities~.,data = seatbelt)
stepAIC(lm1,direction = "both",k=2)
```

BIC
```{r}
library("MASS")
lm1 = lm(fatalities~.,data = seatbelt)
stepAIC(lm1,direction = "both",k=log(523))
```

```{r}
lm2 =lm(formula = fatalities ~ speed70 + alcohol + income + age, data = seatbelt)
summary(lm2)
anova(lm2)
```

```{r}
par(mfrow = c(2,2))
plot(lm2,which = 1)
plot(lm2, which = 2)
p = sum(hatvalues(lm2))
n = length(fatalities)
hat = hatvalues(lm2)
x = (1:n)
plot(x,hat,type ="h" , lwd=2, main ="leverage plot")
h = 2*p/n
abline(h=2*p/n,lwd ="2",col ="red")
cook = cooks.distance(lm2)
plot(cook,type ="h" , lwd=2,cex.lab =1.5)
```

## sqrt()

```{r}
y = sqrt(fatalities)
lm3 =lm(y~1)
stepAIC(lm3,y~speed70 + alcohol + income + age,direction = "both",k=log(523))
```

```{r}
lm4= lm(formula = y ~ income + age + speed70 + alcohol)
summary(lm4)
anova(lm4)
```

```{r}
par(mfrow = c(2,2))
plot(lm4,which = 1)
plot(lm4, which = 2)
p = sum(hatvalues(lm4))
n = length(fatalities)
hat = hatvalues(lm4)
x = (1:n)
plot(x,hat,type ="h" , lwd=2, main ="leverage plot")
h = 2*p/n
abline(h=2*p/n,lwd ="2",col ="red")
cook = cooks.distance(lm4)
plot(cook,type ="h" , lwd=2,cex.lab =1.5)

```

# predict

```{r}
newdata = data.frame()
predict(lm2,newdata = ,interval = "prediction",level = 0.95)
```



# ridge estimation and lasso


```{r}
library(caret)
library(glmnet)
library(Metrics)
```

```{r}
seatbelt[seatbelt=="yes"]=1
seatbelt[seatbelt=="no"]=1
```

```{r}
set.seed(3022)
d_index = createDataPartition(seatbelt$fatalities, p=0.7)
train_d = seatbelt[d_index$Resample1,]
test_d = seatbelt[d_index$Resample1,]
```

```{r}
scal =preProcess(train_d,method = c("center","scale"))
train_ds = predict(scal,train_d)
test_ds =  predict(scal,test_d)
```

```{r}
lambdas = seq(0,2,length.out=100)
x =data.matrix(train_ds[,c(1:2),(4:12)])
y = test_ds[,"fatalities"]
```

## lassomodel
```{r}
lasso_model = cv.glmnet(x,y,family = "gaussian", alpha=1, lambda = lambdas, nfolds = 3)
plot(lasso_model)
plot(lasso_model$glmnet.fit,"lambda",label =T)
```

```{r}
lasso_min = lasso_model$lambda.min
lasso_min
lasso_best = glmnet(x,y,alpha = 1,lambda =lasso_min)
coefficients(lasso_best)
```
## ridgemodel

```{r}
ridge_model = cv.glmnet(x,y,family = "gaussian", alpha=0, lambda = lambdas, nfolds = 3)
plot(ridge_model)
plot(ridge_model$glmnet.fit,"lambda",label =T)
```

```{r}
ridge_min = ridge_model$lambda.min
ridge_min
ridge_best = glmnet(x,y,alpha = 1,lambda =lasso_min)
coefficients(ridge_best)
```



## box-cox
```{r}
library(MASS)
par(mfrow =c(1,2))
boxcox(lm2,plotit =T)
boxcox(lm2,plotit =T,lambda =seq(-0.25,0.5,by =0.2))
```
```{r}
y =log(fatalities)

```

